title: Yishan Li # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here

<a href="https://www.linkedin.com/in/yishanamy-li/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
