title: Yishan Li # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  I am completing my master degree(data science and artificial intelligence) at the University of Waterloo. After finishing my Bachelor's of Computer Science from Queen's University, my interest in exploring more in the data science field and learning how the advanced technology has been driving the future brought me to the University of Waterloo.
My internship experience at IBM has provided me with real-life experience, important technological skills, strong analytical and problem-solving skills that work for companies of any size. A world-class education at both Queen's University and the University of Waterloo has equipped me with the premium learning experience and valuable insights for the future.
I am constantly looking for internship opportunities that I could contribute my skill-set to the field, at the same time learn more advanced technology. 
  <br><br>
  <a href="https://www.linkedin.com/in/yishanamy-li//">View My LinkedIn Profile</a> 

