title: Yishan Li # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here

<a href="https://www.linkedin.com/in/yishanamy-li//">View My LinkedIn Profile</a> 
<a href="https://github.com/liyishanamy//">View My Github</a> 


